/*
COMPAÑEROS PARA GENERAR LOS REPORTES DE VENTA SE NECESITAN COLOCAR ESTAS LIBRERIAS ADJUNTADAS DE 
APACHE POI PARA QUE FUNCIONE CORRECTAMENTE, TAMBIEN COLOCAR EN LA VISTA UN BOTON:

EJEMPLO:
public void generar_( ArrayList<Venta> ge, ArrayList<Cliente> cl){      
    generar_reportes(ge, cl); DAR ACCESO A LAS LISTAS DE VENTA Y CLIENTE
}

*NOTA: SE GENERARAN REPORTES DE VENTAS ANUALES POR LO TANTO CADA VEZ QUE UTILICE LOS OBJETOS CREADOS, EL PROGRAMA TIENE QUE
GENERAR EL REPORTE DE VENTA QUE SERA DEL MOMENTO ELABORADO DEL DIA.

EJEMPLO: REPORTE DEL DIA 19/02/2018 12:02 PM

LOS NOMBRES DE LOS REPORTES TIENE "ReporteProductos (un numero aleatorio de 1 a 99999999).xlsx"

NECESITA EL ACCESO A LISTA DE OBJETOS CREADOS DE CLIENTE Y DE VENTAS PARA EXTRAER LOS DATOS AL REPORTE DE VENTAS.

POR DEFECTO LO GUARDA EN LA CARPETA DEL PROYECTO realizarReportes//

para agregar las librerias Tools/Libreries/ New Library con el nombre: Apache POI /.... AGREGAN CADA LIBRERIA QUE NECESITA
*/

package utils.realizarreportes;
/* PARTE DE GUILLERMO MARROQUIN PARA GENERAR REPORTE DE VENTA EN EXCEL GRUPO 1 PROGRAMACION 3*/

public class RealizarReportes {
    /**
     * @param args the command line arguments
     */
    public static void main(String [] args ){
      GestorVenta v = new GestorVenta();
      v.crear_reporte();//PRUEBA DE OBJETOS DE CLIENTE Y VENTA
      v.generar_reporte();//PRUEBA DE GENERADOR DE REPORTES DE VENTAS
    }

}
