package view;


import java.io.FileNotFoundException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Cliente;
import model.DbData;
import model.Documento;
import utils.Utils;
import utils.realizarreportes.GestorVenta;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Erick
 */
public class Index extends javax.swing.JFrame {
    int Monto;
    private DbData<Cliente> clienteController;
    private Cliente cliente;
    /**
     * Creates new form Index
     */
    public Index() {
        initComponents();
        clienteController = new DbData(Cliente.class,"cliente.txt");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cantidad = new javax.swing.JSpinner();
        LblCantidad = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LblPrecio = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LblTotal = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        FormaPago = new javax.swing.JComboBox<>();
        Aceptar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Rcontado = new javax.swing.JMenuItem();
        Rcredito = new javax.swing.JMenuItem();
        Rtarjeta = new javax.swing.JMenuItem();
        RCheque = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio");

        cantidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cantidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cantidadStateChanged(evt);
            }
        });

        LblCantidad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Cantidad de Producto a Cobrar.");

        jLabel2.setText("Cantidad de Helados:");

        jLabel3.setText("Precio Unitario:");

        LblPrecio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel4.setText("TOTAL:");

        LblTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblTotal.setForeground(new java.awt.Color(255, 51, 0));

        jLabel5.setText("Codigo de Cliente:");

        FormaPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Contado", "Credito", "Tarjeta Credito", "Cheque" }));

        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        jLabel6.setText("Forma de Pago:");

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("Inicio");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Bloquear");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Reportes");

        Rcontado.setText("Contado");
        Rcontado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RcontadoActionPerformed(evt);
            }
        });
        jMenu2.add(Rcontado);

        Rcredito.setText("Credito");
        Rcredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RcreditoActionPerformed(evt);
            }
        });
        jMenu2.add(Rcredito);

        Rtarjeta.setText("Tarjeta");
        Rtarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RtarjetaActionPerformed(evt);
            }
        });
        jMenu2.add(Rtarjeta);

        RCheque.setText("Cheque");
        RCheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RChequeActionPerformed(evt);
            }
        });
        jMenu2.add(RCheque);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Caja");

        jMenuItem4.setText("Corte de Caja");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(LblCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel3))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(40, 40, 40)
                                                .addComponent(Aceptar))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(FormaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNombre))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(lblNombre)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNombre)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(LblCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(LblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(LblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FormaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(Aceptar)
                .addGap(39, 39, 39))
        );

        txtNombre.getAccessibleContext().setAccessibleName("txtCodigo");
        jButton1.getAccessibleContext().setAccessibleName("btnBuscar");
        lblNombre.getAccessibleContext().setAccessibleName("lblNombre");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cantidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cantidadStateChanged
        // TODO add your handling code here:
        LblCantidad.setText(cantidad.getValue().toString());
        int PRECIO;
        
        int cant = Integer.parseInt(cantidad.getValue().toString());
        if(cant>=100)
        {
         PRECIO=4;   
        }
        else{
            PRECIO = 5;
        }
        LblPrecio.setText(Integer.toString(PRECIO));
        Monto =(cant*PRECIO);
        LblTotal.setText(Integer.toString(Monto));
        
        
    }//GEN-LAST:event_cantidadStateChanged

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        // TODO add your handling code here:
        if(cliente!=null  && Integer.parseInt(cantidad.getValue().toString())>0){
            Documento documento = new Documento();
            Calendar c = Calendar.getInstance();
            documento.setCliente(cliente);
            documento.setFecha(c.getTime());
            documento.setSerie("A");
            documento.setTotalDocumento(Monto);
            if("Contado".equals(FormaPago.getSelectedItem().toString())){
                 PagoContado iniciar = new PagoContado(documento);
                 iniciar.LblMonto.setText(Integer.toString(Monto));
                iniciar.setVisible(true);
            }else if("Tarjeta Credito".equals(FormaPago.getSelectedItem().toString())){
                PagoTarjeta iniciar = new PagoTarjeta(documento);
                iniciar.lblMonto.setText(Integer.toString(Monto));
                iniciar.setVisible(true);
            }else if("Cheque".equals(FormaPago.getSelectedItem().toString())){
                PagoCheque iniciar = new PagoCheque(documento);
                iniciar.lblMonto.setText(Integer.toString(Monto));
                iniciar.setVisible(true);
            }else{
                PagoCredito iniciar = new PagoCredito(documento);
                iniciar.LblMonto.setText(Integer.toString(Monto));
                     //iniciar..setText(txtCodigoCliente.getText());
                iniciar.setVisible(true);
            }
        }else{
            JOptionPane.showMessageDialog(null,"Dato Incorrecto \n"
                    +"porfavor ingrese un dato Correcto",
                    "Dato Incorrecto", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_AceptarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            cliente = Utils.findCliente(txtNombre.getText().toLowerCase());
            if(cliente != null)
               lblNombre.setText(cliente.getNombre());
            else{
                int op=JOptionPane.showOptionDialog(null, //Component parentComponent
                               "No se encontro ningun cliente con este codigo, Desea crearlo?", //Object message,
                               "Dato no encontrado", //String title
                               JOptionPane.YES_NO_OPTION, //int optionType
                               JOptionPane.INFORMATION_MESSAGE, //int messageType
                               null, //Icon icon,
                               new String[]{"Si","No"}, //Object[] options,
                               "Si");//Object initialValue 
                if(op==0){
                    CrearCliente frmCliente = new CrearCliente();
                    frmCliente.setVisible(true);
                    frmCliente.lblCodigo.setText(txtNombre.getText());
                }
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Index.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new JDLogin(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void RcontadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RcontadoActionPerformed
        // TODO add your handling code here:
        ReporteContado reportar = new ReporteContado();
        reportar.setVisible(true);
    }//GEN-LAST:event_RcontadoActionPerformed

    private void RcreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RcreditoActionPerformed
        // TODO add your handling code here:
        ReporteCredito reportar = new ReporteCredito();
        reportar.setVisible(true);
    }//GEN-LAST:event_RcreditoActionPerformed

    private void RtarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RtarjetaActionPerformed
        // TODO add your handling code here:
        ReporteTarjeta reportar = new ReporteTarjeta();
        reportar.setVisible(true);
    }//GEN-LAST:event_RtarjetaActionPerformed

    private void RChequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RChequeActionPerformed
        // TODO add your handling code here:
        ReporteCheques reportar = new ReporteCheques();
        reportar.setVisible(true);
    }//GEN-LAST:event_RChequeActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        GestorVenta v = new GestorVenta();
      
        try {
            v.generar_reporte();//PRUEBA DE GENERADOR DE REPORTES DE VENTAS
            JOptionPane.showMessageDialog(null,"Reporte generado exitosamente",
                    "Resultado Exitoso", JOptionPane.INFORMATION_MESSAGE);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Index.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JComboBox<String> FormaPago;
    private javax.swing.JLabel LblCantidad;
    private javax.swing.JLabel LblPrecio;
    private javax.swing.JLabel LblTotal;
    private javax.swing.JMenuItem RCheque;
    private javax.swing.JMenuItem Rcontado;
    private javax.swing.JMenuItem Rcredito;
    private javax.swing.JMenuItem Rtarjeta;
    private javax.swing.JSpinner cantidad;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    private void exit(int i) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
