package view;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.DbData;
import model.Detalle;
import model.Documento;
import model.Producto;
import model.TipoPago;
import model.TipoTransaccion;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Erick
 */
public class PagoCheque extends javax.swing.JFrame {

    private Documento documento;  
    private Producto producto;
    private final DbData<Documento> documentoController;
    private final DbData<Detalle> detalleController;
    /**
     * Creates new form PagoCheque
     */
    public PagoCheque() {
        initComponents();
        documentoController = new DbData(Documento.class, "documento.txt");
        detalleController = new DbData(Detalle.class, "detalle.txt");
    }

    public PagoCheque(Documento documento){
        initComponents();
        this.documento = documento;
        documentoController = new DbData(Documento.class, "documento.txt");
        detalleController = new DbData(Detalle.class, "detalle.txt");
        producto = new Producto();
        producto.setCodigo("P0001");
        producto.setDescripcion("Helado");
        producto.setPrecio(5.00);
        producto.setId(1);
        producto.setStock(100);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Transaccion = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtNumeroCheque = new javax.swing.JTextField();
        txtNumeroCuenta = new javax.swing.JTextField();
        Bancos = new javax.swing.JComboBox<>();
        lblMonto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("PAGO CON CHEQUE");

        jLabel2.setText("Nota:Al no contar  con fondos tendra un recargo de Q100.00  por gastos Administrativos.");

        jLabel3.setText("Numero de Cheque:");

        jLabel4.setText("Numero de Cuenta:");

        jLabel5.setText("Banco:");

        jLabel6.setText("Monto:");

        Transaccion.setText("Realizar Transaccion");
        Transaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransaccionActionPerformed(evt);
            }
        });

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Bancos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Banco...", "Banco de Desarrollo Rural.", "Banco de los Trabajadores.", "Banco Industrial", "Banco Reformador.", "Banco G & T Continental." }));

        lblMonto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMonto.setForeground(new java.awt.Color(0, 0, 153));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumeroCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNumeroCuenta)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Bancos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(Transaccion))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNumeroCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNumeroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(Bancos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(lblMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Transaccion)
                .addGap(7, 7, 7)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TransaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransaccionActionPerformed
        // TODO add your handling code here:
        if(txtNumeroCheque.getText().length()!=0 && txtNumeroCuenta.getText().length() !=0){
            if("Seleccione Banco...".equals(Bancos.getSelectedItem().toString())){
                JOptionPane.showMessageDialog(null,"Seleccione Banco del Cliente"
                        ,"Seleccione ", JOptionPane.ERROR_MESSAGE);  
            }else{
                try {
                    int idDocumento, idDetalle;
                    List<Documento> d = documentoController.getAll();
                    List<TipoPago> pago = new ArrayList();
                    pago.add(TipoPago.CHEQUE);
                    List<Detalle> detalleList = detalleController.getAll();
                    d.sort((d1,d2)-> d2.getId()-d1.getId());
                    detalleList.sort((det1, det2)-> det2.getId()-det1.getId());
                   
                    if(detalleList.isEmpty()) idDetalle = 1;
                    else idDetalle = detalleList.get(0).getId()+1;
                   
                    if(d.isEmpty()) idDocumento = 1;
                    else idDocumento = d.get(0).getId()+1;
                   
                    documento.setId(idDocumento);
                    documento.setTipoPago(pago);
                    documento.setDocumento(txtNumeroCheque.getText());
                    Detalle transaccion = new Detalle();
                    transaccion.setId(idDetalle);
                    transaccion.setDocumento(documento);
                    transaccion.setTipoTransaccion(TipoTransaccion.VENTA);
                    transaccion.setTotal(documento.getTotalDocumento());
                    transaccion.setProducto(producto);
                
                    documentoController.add(documento);
                    detalleController.add(transaccion);
                    JOptionPane.showMessageDialog(null, "Transaccion realizada con exito"
                    ,"Operacion Exitosa", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                } catch (IOException ex) {
                    Logger.getLogger(PagoCheque.class.getName()).log(Level.SEVERE, null, ex);
                }
                   
            }
        }else{
            JOptionPane.showMessageDialog(null,"Ingrese Datos del Cliente"
            ,"Ingresar Datos", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_TransaccionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PagoCheque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PagoCheque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PagoCheque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagoCheque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PagoCheque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Bancos;
    private javax.swing.JButton Transaccion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel lblMonto;
    private javax.swing.JTextField txtNumeroCheque;
    private javax.swing.JTextField txtNumeroCuenta;
    // End of variables declaration//GEN-END:variables
}
