package view;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.DbData;
import model.Detalle;
import model.Documento;
import model.Producto;
import model.TipoPago;
import model.TipoTransaccion;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Erick
 */
public class PagoContado extends javax.swing.JFrame {
    //private int monto;
    private Documento documento;  
    private Producto producto;
    private final DbData<Documento> documentoController;
    private final DbData<Detalle> detalleController;
    /**
     * Creates new form PagoContado
     * @param documento datos del encabezado del documento
     */
    public PagoContado(Documento documento) {
        initComponents();
        this.documento = documento;
        documentoController = new DbData(Documento.class, "documento.txt");
        detalleController = new DbData(Detalle.class, "detalle.txt");
        producto = new Producto();
        producto.setCodigo("P0001");
        producto.setDescripcion("Helado");
        producto.setPrecio(5.00);
        producto.setId(1);
        producto.setStock(100);
    }
    public PagoContado(){
        initComponents();
        documentoController = new DbData(Documento.class, "documento.txt");
        detalleController = new DbData(Detalle.class, "detalle.txt");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BtnTransaccion = new javax.swing.JButton();
        LblMonto = new javax.swing.JLabel();
        LblCambio = new javax.swing.JLabel();
        txtEfectivo = new javax.swing.JTextField();
        Regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("PAGO CONTADO");

        jLabel2.setText("Monto a Pagar:");

        jLabel3.setText("Efectivo");

        jLabel4.setText("Cambio");

        BtnTransaccion.setText("Realizar Transaccion");
        BtnTransaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTransaccionActionPerformed(evt);
            }
        });

        LblMonto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblMonto.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                LblMontoComponentAdded(evt);
            }
        });

        LblCambio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblCambio.setForeground(new java.awt.Color(255, 51, 0));

        txtEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEfectivoActionPerformed(evt);
            }
        });

        Regresar.setText("Regresar");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(BtnTransaccion))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(LblCambio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LblMonto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtEfectivo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(Regresar)))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LblMonto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(LblCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(BtnTransaccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Regresar)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LblMontoComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_LblMontoComponentAdded
        // TODO add your handling code here:
      //  LblMonto.setText(Monto);
    }//GEN-LAST:event_LblMontoComponentAdded

    private void txtEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEfectivoActionPerformed
        // TODO add your handling code here:        
        int Cambio, efectivo, monto;
        monto=Integer.parseInt(LblMonto.getText());
        efectivo=Integer.parseInt(txtEfectivo.getText());
        if(efectivo<monto){
                   JOptionPane.showMessageDialog(null,"Efectivo Faltante \n"
            +"porfavor ingrese monto valido",
                    "Monto Invalido", JOptionPane.ERROR_MESSAGE);  
        }
        else{
        Cambio=efectivo-monto;
        LblCambio.setText(Integer.toString(Cambio));
        }
    }//GEN-LAST:event_txtEfectivoActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_RegresarActionPerformed

    private void BtnTransaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTransaccionActionPerformed
        // TODO add your handling code here:
        if(txtEfectivo.getText().length()!=0){
           if(Integer.parseInt(txtEfectivo.getText())<Integer.parseInt(LblMonto.getText())){
                   JOptionPane.showMessageDialog(null,"Efectivo Faltante \n"
            +"porfavor ingrese monto valido",
                    "Monto Invalido", JOptionPane.ERROR_MESSAGE);  
            }else{
               try {
                   int idDocumento, idDetalle;
                   List<TipoPago> pago = new ArrayList();
                   pago.add(TipoPago.EFECTIVO);
                   List<Documento> d = documentoController.getAll();
                   List<Detalle> detalleList = detalleController.getAll();
                   d.sort((d1,d2)-> d2.getId()-d1.getId());
                   detalleList.sort((det1, det2)-> det2.getId()-det1.getId());
                   
                   if(detalleList.isEmpty()) idDetalle = 1;
                   else idDetalle = detalleList.get(0).getId()+1;
                   
                   if(d.isEmpty()) idDocumento = 1;
                   else idDocumento = d.get(0).getId()+1;
                   
                   documento.setId(idDocumento);
                   documento.setTipoPago(pago);
                   Detalle transaccion = new Detalle();
                   transaccion.setId(idDetalle);
                   transaccion.setDocumento(documento);
                   transaccion.setTipoTransaccion(TipoTransaccion.VENTA);
                   transaccion.setTotal(documento.getTotalDocumento());
                   transaccion.setProducto(producto);
                   documentoController.add(documento);
                   detalleController.add(transaccion);
                   JOptionPane.showMessageDialog(null, "Transaccion realizada con exito"
                   ,"Operacion Exitosa", JOptionPane.INFORMATION_MESSAGE);
                   this.dispose();
               } catch (FileNotFoundException ex) {
                   Logger.getLogger(PagoContado.class.getName()).log(Level.SEVERE, null, ex);
               } catch (IOException ex) {
                   Logger.getLogger(PagoContado.class.getName()).log(Level.SEVERE, null, ex);
               }
            }
            
        }else{
            JOptionPane.showMessageDialog(null,"Ingresar Efectivo \n"
            +"porfavor ingrese monto de Efectivo",
                    "Ingresar Efectivo", JOptionPane.ERROR_MESSAGE);      
        }
    }//GEN-LAST:event_BtnTransaccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagoContado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PagoContado().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnTransaccion;
    private javax.swing.JLabel LblCambio;
    public static javax.swing.JLabel LblMonto;
    private javax.swing.JButton Regresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtEfectivo;
    // End of variables declaration//GEN-END:variables
}
