package view;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.CuentaCorriente;
import model.DbData;
import model.Detalle;
import model.Documento;
import model.Producto;
import model.TipoPago;
import model.TipoTransaccion;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Erick
 */
public class PagoCredito extends javax.swing.JFrame {
    private Documento documento;  
    private Producto producto;
    private final DbData<Documento> documentoController;
    private final DbData<Detalle> detalleController;
    private final DbData<CuentaCorriente> creditoController;
    /**
     * Creates new form PagoCredito
     */
    public PagoCredito() {
        initComponents();
        documentoController = new DbData(Documento.class, "documento.txt");
        detalleController = new DbData(Detalle.class, "detalle.txt");
        creditoController = new DbData(CuentaCorriente.class, "credito.txt");
        producto = new Producto();
        producto.setCodigo("P0001");
        producto.setDescripcion("Helado");
        producto.setPrecio(5.00);
        producto.setId(1);
        producto.setStock(100);
    }
    
    /**
     * Creates new form PagoCredito
     * @param documento documento
     */
    public PagoCredito(Documento documento){
        initComponents();
        this.documento = documento;
        txtCodigoCliente.setText(documento.getCliente().getCodigoCliente());
        LblNombre.setText(documento.getCliente().getNombre());
        documentoController = new DbData(Documento.class, "documento.txt");
        detalleController = new DbData(Detalle.class, "detalle.txt");
        creditoController = new DbData(CuentaCorriente.class, "credito.txt");
        producto = new Producto();
        producto.setCodigo("P0001");
        producto.setDescripcion("Helado");
        producto.setPrecio(5.00);
        producto.setId(1);
        producto.setStock(100);
    }

    PagoCredito(String toString) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    PagoCredito(int Monto) {
        
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCodigoCliente = new javax.swing.JTextField();
        txtNumeroCredito = new javax.swing.JTextField();
        LblMonto = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LblNombre = new javax.swing.JLabel();
        SolicitudCredito = new javax.swing.JButton();
        Regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("PAGO CREDITO.");

        jLabel2.setText("Monto a Acreditar:");

        jLabel3.setText("Codigo Cliente:");

        jLabel4.setText("No. Nota de Credito:");

        txtCodigoCliente.setEditable(false);

        LblMonto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LblMonto.setForeground(new java.awt.Color(51, 0, 204));

        jLabel5.setText("Nombre Cliente:");

        LblNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LblNombre.setForeground(new java.awt.Color(0, 0, 204));

        SolicitudCredito.setText("Solicitar Credito");
        SolicitudCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SolicitudCreditoActionPerformed(evt);
            }
        });

        Regresar.setText("Regresar");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(124, 124, 124)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(41, 41, 41)
                                    .addComponent(txtCodigoCliente))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtNumeroCredito))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(37, 37, 37)
                                            .addComponent(LblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(SolicitudCredito)
                                                .addComponent(LblMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(0, 0, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(Regresar)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(LblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNumeroCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(LblMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SolicitudCredito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Regresar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_RegresarActionPerformed

    private void SolicitudCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SolicitudCreditoActionPerformed
        try {
            // TODO add your handling code here:
            int idDocumento, idDetalle, idCredito;
            Calendar c = Calendar.getInstance();
            List<Documento> d = documentoController.getAll();
            List<TipoPago> pago = new ArrayList();
            CuentaCorriente cuentaCorriente = new CuentaCorriente();
            List<CuentaCorriente> cuentaList = creditoController.getAll();
            pago.add(TipoPago.CxC);
            List<Detalle> detalleList = detalleController.getAll();
            d.sort((d1,d2)-> d2.getId()-d1.getId());
            detalleList.sort((det1, det2)-> det2.getId()-det1.getId());
            cuentaList.sort((cuenta1, cuenta2)-> cuenta2.getId()-cuenta1.getId());
            if(detalleList.isEmpty()) idDetalle = 1;
            else idDetalle = detalleList.get(0).getId()+1;

            if(d.isEmpty()) idDocumento = 1;
            else idDocumento = d.get(0).getId()+1;
            if(cuentaList.isEmpty()) idCredito = 1;
            else idCredito = cuentaList.get(0).getId() + 1;
            
            cuentaCorriente.setId(idCredito);
            cuentaCorriente.setCargo(documento.getTotalDocumento());
            cuentaCorriente.setAbono(0.00);
            cuentaCorriente.setCliente(documento.getCliente());
            cuentaCorriente.setDocumento(documento);
            cuentaCorriente.setFecha(c.getTime());
            
            documento.setId(idDocumento);
            documento.setTipoPago(pago);
            documento.setDocumento(txtNumeroCredito.getText());
            Detalle transaccion = new Detalle();
            transaccion.setId(idDetalle);
            transaccion.setDocumento(documento);
            transaccion.setTipoTransaccion(TipoTransaccion.VENTA);
            transaccion.setTotal(documento.getTotalDocumento());
            transaccion.setProducto(producto);

            documentoController.add(documento);
            detalleController.add(transaccion);
            JOptionPane.showMessageDialog(null, "Transaccion realizada con exito"
            ,"Operacion Exitosa", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            creditoController.add(cuentaCorriente);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PagoCredito.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(PagoCredito.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SolicitudCreditoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PagoCredito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PagoCredito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PagoCredito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagoCredito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PagoCredito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel LblMonto;
    public static javax.swing.JLabel LblNombre;
    private javax.swing.JButton Regresar;
    private javax.swing.JButton SolicitudCredito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtCodigoCliente;
    private javax.swing.JTextField txtNumeroCredito;
    // End of variables declaration//GEN-END:variables
}
